//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D5MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDa
    {
        public int OrderID { get; set; }
        [Required]
        public Nullable<int> CustomerID { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public Nullable<System.DateTime> OrderData { get; set; }
    
        public virtual CustomerMVC CustomerMVC { get; set; }
    }
}
