//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCD2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maping
    {
        public Nullable<decimal> Long { get; set; }
        public Nullable<decimal> Lite { get; set; }
        public int ID { get; set; }
    }
}
