//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<categories1> categories1 { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<CorStd> CorStds { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CustomerMVC> CustomerMVCs { get; set; }
        public virtual DbSet<D3MVC> D3MVC { get; set; }
        public virtual DbSet<MVCStudent> MVCStudents { get; set; }
        public virtual DbSet<order1> order1 { get; set; }
        public virtual DbSet<OrderDa> OrderDas { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<RolLogin> RolLogins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
        public virtual DbSet<userReg> userRegs { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<orderProduct> orderProducts { get; set; }
        public virtual DbSet<user1> user1 { get; set; }
    }
}
